/*
 * migrateLegacyApprovals.ts
 *
 * Orchestration for the legacy approval migration script. Extracted from
 * `scripts/migrate-legacy-approvals.ts` so the dry-run, write, and rollback
 * flows can be unit-tested with injected fetch/fs dependencies without
 * touching the network or the filesystem. The CLI script in
 * `scripts/migrate-legacy-approvals.ts` is now a thin wrapper around this
 * library.
 *
 * Behaviour is unchanged: dry-run prints a summary with no DB writes, write
 * POSTs approvals through the canonical endpoint and saves a snapshot for
 * later rollback, and rollback reads a snapshot and DELETEs each row.
 */

import type {
  DetectedApproval,
  MigrationBreakdown,
  MigrationSummary
} from './legacyApprovals.ts';
import {
  detectLegacyApprovals,
  existingApprovalKeys
} from './legacyApprovals.ts';

export type ApprovalType = 'spec' | 'tech_design' | 'qa';

export interface TaskApproval {
  id: string;
  taskId: string;
  type: ApprovalType;
  owner: string;
  state: 'approved' | 'revoked';
  approvedAt: string;
  revokedAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface TaskComment {
  id: string;
  author: string;
  text: string;
  createdAt: string;
  updatedAt: string;
}

export interface MigrationTask {
  id: string;
  title: string;
  description: string | null;
  status: string;
  taskType: string | null;
  approvals: TaskApproval[];
  comments: TaskComment[];
}

export interface SnapshotFile {
  savedAt: string;
  rolledBack: boolean;
  rows: Array<{ taskId: string; type: ApprovalType }>;
}

export interface MigrationDeps {
  fetchAllTasks: () => Promise<MigrationTask[]>;
  postApproval: (taskId: string, approval: DetectedApproval) => Promise<void>;
  deleteApproval: (taskId: string, type: ApprovalType) => Promise<void>;
  writeFile: (path: string, content: string) => void;
  readFile: (path: string) => string;
  ensureDir: (path: string) => void;
}

export interface MigrationRunSummary extends MigrationSummary {
  snapshotPath: string | null;
  dryRun: boolean;
  rolledBack: number;
}

function emptyBreakdown(): MigrationBreakdown[] {
  return [];
}

function bumpBreakdown(
  breakdownByType: MigrationBreakdown[],
  type: ApprovalType,
  existing: boolean
): void {
  let bucket = breakdownByType.find((b) => b.type === type);
  if (!bucket) {
    bucket = { type, created: 0, skippedExisting: 0 };
    breakdownByType.push(bucket);
  }
  if (existing) bucket.skippedExisting += 1;
  else bucket.created += 1;
}

/**
 * Compute the dry-run summary: which rows WOULD be created and which would
 * be skipped because they already exist on the task. No side effects.
 */
export function planMigration(tasks: MigrationTask[]): MigrationSummary {
  const breakdownByType = emptyBreakdown();
  let createdApprovals = 0;
  let skippedExisting = 0;

  for (const task of tasks) {
    const detected = detectLegacyApprovals(task);
    const existing = existingApprovalKeys(task);
    for (const approval of detected) {
      const key = `${task.id}:${approval.type}`;
      const isExisting = existing.has(key);
      bumpBreakdown(breakdownByType, approval.type, isExisting);
      if (isExisting) skippedExisting += 1;
      else createdApprovals += 1;
    }
  }

  return {
    totalTasks: tasks.length,
    createdApprovals,
    skippedExisting,
    breakdownByType
  };
}

/**
 * Run a dry-run. Identical to `planMigration(fetchAllTasks())` but exposed
 * as a separate function so the CLI surface and the test surface match.
 */
export async function runDryRun(deps: MigrationDeps): Promise<MigrationRunSummary> {
  const tasks = await deps.fetchAllTasks();
  const plan = planMigration(tasks);
  return {
    ...plan,
    snapshotPath: null,
    dryRun: true,
    rolledBack: 0
  };
}

/**
 * Run the migration in write mode. POSTs each detected approval that is not
 * already present, accumulates the (taskId, type) pairs that were written,
 * then saves a snapshot file the caller can use for rollback.
 *
 * The snapshot path is generated by `snapshotPathProvider` so the file
 * location stays consistent with the previous script behaviour.
 */
export async function runWrite(
  deps: MigrationDeps,
  snapshotPathProvider: () => string
): Promise<MigrationRunSummary> {
  const tasks = await deps.fetchAllTasks();
  const snapshotRows: Array<{ taskId: string; type: ApprovalType }> = [];
  const breakdownByType = emptyBreakdown();
  let createdApprovals = 0;
  let skippedExisting = 0;

  for (const task of tasks) {
    const detected = detectLegacyApprovals(task);
    const existing = existingApprovalKeys(task);
    for (const approval of detected) {
      const key = `${task.id}:${approval.type}`;
      const isExisting = existing.has(key);
      if (isExisting) {
        skippedExisting += 1;
      } else {
        await deps.postApproval(task.id, approval);
        snapshotRows.push({ taskId: task.id, type: approval.type });
        createdApprovals += 1;
      }
      bumpBreakdown(breakdownByType, approval.type, isExisting);
    }
  }

  const snapshotPath = snapshotPathProvider();
  deps.ensureDir(snapshotPath);
  const payload: SnapshotFile = {
    savedAt: new Date().toISOString(),
    rolledBack: false,
    rows: snapshotRows
  };
  deps.writeFile(snapshotPath, JSON.stringify(payload, null, 2));

  return {
    totalTasks: tasks.length,
    createdApprovals,
    skippedExisting,
    breakdownByType,
    snapshotPath,
    dryRun: false,
    rolledBack: 0
  };
}

/**
 * Run a rollback. Reads the snapshot file and DELETEs each (taskId, type)
 * pair. Throws if the snapshot is missing or malformed.
 */
export async function runRollback(
  deps: MigrationDeps,
  snapshotPath: string
): Promise<MigrationRunSummary> {
  const raw = deps.readFile(snapshotPath);
  const parsed = JSON.parse(raw) as SnapshotFile;
  if (!parsed || !Array.isArray(parsed.rows)) {
    throw new Error(`snapshot at ${snapshotPath} is malformed`);
  }

  for (const row of parsed.rows) {
    await deps.deleteApproval(row.taskId, row.type);
  }

  return {
    totalTasks: 0,
    createdApprovals: 0,
    skippedExisting: 0,
    breakdownByType: [],
    snapshotPath,
    dryRun: false,
    rolledBack: parsed.rows.length
  };
}