#!/usr/bin/env bash
#
# evidence-capture.sh — print the dashboard URLs, alert state queries,
# Grafana screenshot API calls, and closing-PR markdown template Quinn
# needs to attach AC1-AC3 evidence to PR #724 (task 31233a0a).
#
# Outputs:
#   --format md   Markdown template for the closing PR body, with
#                 placeholders for Quinn to drop screenshots/links into.
#   --format sh   Bash commands Quinn can copy-paste to fetch dashboard
#                 snapshots and alert state JSON.
#   --format json Structured manifest of every dashboard/alert (uid,
#                 title, owner, severity, query expression).
#
# Flags:
#   --dry-run     Print absolute Grafana URLs with placeholder host
#                 (https://<grafana-host>/...). Does NOT source
#                 .env.local. Use this to preview the evidence pack.
#   --output <p>  Write to file instead of stdout.
#   --format FMT  md | sh | json (default: md).
#   -h/--help    Show usage.
#
# Quinn runs the bootstrap (`bootstrap-observability.sh all`), then
# runs `./evidence-capture.sh --format md > evidence.md` and pastes
# evidence.md into PR #724's body (or comments it on the task). The
# `sh` output doubles as a runbook she can execute to fetch each
# dashboard snapshot via the Grafana rendering API.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

DASHBOARD_DIR="${SCRIPT_DIR}/grafana/dashboards"
ALERT_DIR="${SCRIPT_DIR}/grafana/alerts"
ENV_LOCAL="${SCRIPT_DIR}/.env.local"

FORMAT="md"
DRY_RUN=false
OUTPUT=""

print_help() {
  sed -n '2,28p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while [ "${#}" -gt 0 ]; do
  case "$1" in
    -h|--help)
      print_help
      exit 0
      ;;
    --dry-run) DRY_RUN=true; shift ;;
    --output)  OUTPUT="$2"; shift 2 ;;
    --format)  FORMAT="$2"; shift 2 ;;
    md|sh|json) FORMAT="$1"; shift ;;
    *) echo "::error::unknown argument: $1" >&2; exit 2 ;;
  esac
done

GRAFANA_HOST=""
GRAFANA_AUTH_HEADER=""
if [ "${DRY_RUN}" = false ]; then
  if [ ! -f "${ENV_LOCAL}" ]; then
    echo "::error::Quinn-owned secret file not found: ${ENV_LOCAL}" >&2
    echo "::error::Re-run with --dry-run to preview without env.local." >&2
    exit 1
  fi
  set -a
  # shellcheck source=/dev/null
  source "${ENV_LOCAL}"
  set +a
  if [ -z "${GRAFANA_CLOUD_PROMETHEUS_URL:-}" ]; then
    echo "::error::GRAFANA_CLOUD_PROMETHEUS_URL not set in .env.local" >&2
    exit 1
  fi
  # Trim trailing slash so URL composition is uniform.
  GRAFANA_HOST="${GRAFANA_CLOUD_PROMETHEUS_URL%/}"
  GRAFANA_AUTH_HEADER="Authorization: ${GRAFANA_CLOUD_PROVISIONING_AUTH:-Authorization: Bearer <unset>}"
else
  GRAFANA_HOST="https://<grafana-host>"
fi

# ---------------------------------------------------------------------------
# Build the artefacts.
# ---------------------------------------------------------------------------

DASHBOARDS_TSV="$(
  for f in "${DASHBOARD_DIR}"/*.json; do
    python3 - "$f" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
uid = d.get('uid', '')
title = d.get('title', '')
print(f"{uid}\t{title}")
PY
  done
)"

ALERTS_TSV="$(
  for f in "${ALERT_DIR}"/*.json; do
    python3 - "$f" <<'PY'
import json, sys
a = json.load(open(sys.argv[1]))
for grp in a.get('groups', []):
    folder = grp.get('folder', '')
    for r in grp.get('rules', []):
        uid = r.get('uid', '')
        title = r.get('title', '')
        labels = r.get('labels', {})
        sev = labels.get('severity', '')
        owner = labels.get('owner', '')
        # extract the Prometheus expression from the first data source
        exprs = []
        for d in r.get('data', []):
            m = d.get('model', {}) or {}
            e = m.get('expr')
            if e:
                exprs.append(e)
        expr = ' | '.join(exprs)
        print(f"{uid}\t{title}\t{folder}\t{sev}\t{owner}\t{expr}")
PY
  done
)"

emit() {
  # When called with arguments (e.g. `emit "string"`), print them.
  # When called with no arguments (e.g. `emit <<EOF ... EOF`), the
  # heredoc body is piped in via stdin and `cat` reads it.
  if [ "$#" -gt 0 ]; then
    printf '%s\n' "$@"
  elif [ -n "${OUTPUT}" ]; then
    cat >> "${OUTPUT}"
  else
    cat
  fi
}

case "${FORMAT}" in
  md)
    emit <<EOF
# Hosted Observability — AC1-AC3 Evidence Pack (task 31233a0a)

> Generated by \`infra/cloud/observability/evidence-capture.sh\`.
> Quinn: paste this file into PR #724's body (or as a task comment) once
> each screenshot / export below has been captured against the live
> hosted Grafana.

## AC1 — Live hosted observability

The following dashboards render live data from \`${FLY_APP:-sindustries-health-probe-staging}\` and the upstream services:

EOF
    while IFS=$'\t' read -r uid title; do
      [ -z "${uid}" ] && continue
      emit <<ENTRY
- **${title}** — ${GRAFANA_HOST}/d/${uid}  *(paste screenshot here)*
ENTRY
    done <<< "${DASHBOARDS_TSV}"

    emit <<'EOF'

### Prometheus scrape health (confirms OTLP->Prometheus pipeline is live)

- `\${GRAFANA_CLOUD_PROMETHEUS_URL}/api/v1/query?query=up{job="health-probe"}` — expect `1`
- `\${GRAFANA_CLOUD_PROMETHEUS_URL}/api/v1/query?query=sindustries_db_up` — expect at least one series
- `\${GRAFANA_CLOUD_PROMETHEUS_URL}/api/v1/query?query=sindustries_fly_app_health` — expect at least one series

> Paste the JSON output of each query above. They confirm the hosted
> Grafana is receiving OTLP traffic from the deployed health-probe.

## AC2 — Real failure → alert fires → alert resolves

For each scenario below, the operator (Quinn) ran the matching
\`failure-inject.sh <scenario>\` against staging, captured the
alert state transitions, and pasted them here.

EOF
    while IFS=$'\t' read -r uid title folder sev owner expr; do
      [ -z "${uid}" ] && continue
      emit <<ENTRY
### ${title}  (severity=${sev}, owner=${owner})

- **Query expression:** \`${expr}\`
- **Alert state API:** \`${GRAFANA_HOST}/api/v1/provisioning/alert-rules/${uid}/state\`
- **Grafana UI:** \`${GRAFANA_HOST}/alerting/grafana/${uid}/view\`
- **Expected behaviour:**
  - *Injected failure:* (paste scenario + timestamp)
  - *Firing observed at:* (paste alert state JSON or screenshot)
  - *Resolved at:* (paste alert state JSON or screenshot)

ENTRY
    done <<< "${ALERTS_TSV}"

    emit <<'EOF'
## AC3 — Operator diagnoses a failed workflow without the local dev machine

Walk through one real induced failure (see `failure-inject.sh <scenario>`)
and paste evidence for each step below:

1. **Operator opens the cloud-overview dashboard** — confirms the broken service is `up=0` (screenshot).
2. **Operator opens the matching alert detail page** — confirms the alert is `firing` with the expected expression result (screenshot).
3. **Operator opens Tempo traces for the failing service** — pastes the trace ID + screenshot showing the failing span (no logins to the local dev machine were used).
4. **Operator restores the service** (matching recover command from `failure-inject.sh`) — pastes the alert-resolved state JSON.

## AC4 — Evidence index

- AC1 screenshots: (paste per dashboard above)
- AC2 alert-state JSON exports: (paste per alert above)
- AC3 diagnostic walkthrough: (paste screenshots above)
- This file is the evidence manifest linking the three ACs to the artefacts below.

EOF
    ;;

  sh)
    emit <<EOF
#!/usr/bin/env bash
# Runbook generated by infra/cloud/observability/evidence-capture.sh.
# Quinn: source .env.local before running, or set the two vars below.

: "\${GRAFANA_CLOUD_PROMETHEUS_URL:?must be set}"
: "\${GRAFANA_CLOUD_PROVISIONING_AUTH:?must be set}"

OUT="\${1:-./observability-evidence}"
mkdir -p "\${OUT}"

dashboards=(
EOF
    while IFS=$'\t' read -r uid title; do
      [ -z "${uid}" ] && continue
      emit <<ENTRY
  "${uid}|${title}"
ENTRY
    done <<< "${DASHBOARDS_TSV}"
    emit <<'EOF'
)

alerts=(
EOF
    while IFS=$'\t' read -r uid title folder sev owner expr; do
      [ -z "${uid}" ] && continue
      emit <<ENTRY
  "${uid}|${title}|${sev}|${owner}"
ENTRY
    done <<< "${ALERTS_TSV}"
    emit <<'EOF'
)

for entry in "${dashboards[@]}"; do
  uid="\${entry%%|*}"
  curl --fail --silent --show-error \\
    -H "Authorization: \${GRAFANA_CLOUD_PROVISIONING_AUTH}" \\
    "\${GRAFANA_CLOUD_PROMETHEUS_URL%/}/api/dashboards/uid/\${uid}" \\
    -o "\${OUT}/dashboard-\${uid}.json"
  curl --fail --silent --show-error \\
    -H "Authorization: \${GRAFANA_CLOUD_PROVISIONING_AUTH}" \\
    "\${GRAFANA_CLOUD_PROMETHEUS_URL%/}/api/dashboards/uid/\${uid}/export" \\
    -o "\${OUT}/dashboard-\${uid}-export.json"
done

for entry in "${alerts[@]}"; do
  IFS='|' read -r uid title sev owner <<< "\${entry}"
  curl --fail --silent --show-error \\
    -H "Authorization: \${GRAFANA_CLOUD_PROVISIONING_AUTH}" \\
    "\${GRAFANA_CLOUD_PROMETHEUS_URL%/}/api/v1/provisioning/alert-rules/\${uid}" \\
    -o "\${OUT}/alert-\${uid}.json"
  curl --fail --silent --show-error \\
    -H "Authorization: \${GRAFANA_CLOUD_PROVISIONING_AUTH}" \\
    "\${GRAFANA_CLOUD_PROMETHEUS_URL%/}/api/v1/provisioning/alert-rules/\${uid}/state" \\
    -o "\${OUT}/alert-\${uid}-state.json"
done

echo "Evidence fetched to \${OUT}/"
EOF
    ;;

  json)
    emit <<EOF
{
  "generatedBy": "infra/cloud/observability/evidence-capture.sh",
  "grafanaHost": "${GRAFANA_HOST}",
  "flyApp": "${FLY_APP:-sindustries-health-probe-staging}",
  "dashboards": [
EOF
    first=true
    while IFS=$'\t' read -r uid title; do
      [ -z "${uid}" ] && continue
      sep="$( [ "${first}" = true ] && echo "" || echo "," )"
      emit "${sep}    {\"uid\":\"${uid}\",\"title\":\"${title}\",\"url\":\"${GRAFANA_HOST}/d/${uid}\"}"
      first=false
    done <<< "${DASHBOARDS_TSV}"
    emit <<'EOF'

  ],
  "alerts": [
EOF
    first=true
    while IFS=$'\t' read -r uid title folder sev owner expr; do
      [ -z "${uid}" ] && continue
      # JSON-escape the expression for embedding.
      expr_escaped="$(printf '%s' "${expr}" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')"
      sep="$( [ "${first}" = true ] && echo "" || echo "," )"
      emit "${sep}    {\"uid\":\"${uid}\",\"title\":\"${title}\",\"folder\":\"${folder}\",\"severity\":\"${sev}\",\"owner\":\"${owner}\",\"expr\":${expr_escaped},\"url\":\"${GRAFANA_HOST}/alerting/grafana/${uid}/view\",\"stateApi\":\"${GRAFANA_HOST}/api/v1/provisioning/alert-rules/${uid}/state\"}"
      first=false
    done <<< "${ALERTS_TSV}"
    emit <<'EOF'

  ]
}
EOF
    ;;

  *)
    echo "::error::unknown format: ${FORMAT}" >&2
    exit 2
    ;;
esac
