#!/usr/bin/env python3
"""
Step 4 of sindustries-weekly-review lobster.

Commits the weekly review file to a branch and opens a PR against brain/reviews/.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[5]


def run(cmd: list[str], cwd: Path = WORKSPACE, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, check=check)


def main() -> None:
    parser_args = sys.argv[1:]
    dry_run = "--dry-run" in parser_args

    stdin_data = json.load(sys.stdin)
    review_path_str = stdin_data.get("review_path", "")
    review_date = stdin_data.get("review_date", "unknown")
    daily_notes_count = stdin_data.get("daily_notes_count", 0)

    branch = f"content/weekly-review-{review_date}"

    if dry_run:
        result = {
            **stdin_data,
            "branch": branch,
            "pr_url": None,
            "dry_run": True,
        }
        print(json.dumps(result))
        return

    # Create branch off main
    run(["git", "checkout", "main"])
    run(["git", "checkout", "-b", branch], check=False)

    # Stage the review file
    run(["git", "add", review_path_str])

    # Commit
    commit_msg = f"content(weekly-review): {review_date} weekly review\n\nTom's notes + {daily_notes_count} daily note(s) from heartbeat."
    run(["git", "commit", "-m", commit_msg])

    # Push
    run(["git", "push", "-u", "origin", branch])

    # Open PR
    pr_body = (
        f"## Weekly SIndustries review — {review_date}\n\n"
        "Review the **Needs approval from Tom** and **Needs approval from Quinn** sections.\n\n"
        "Approve and merge to convert items into content tasks.\n\n"
        f"Daily notes accumulated: {daily_notes_count}\n\n"
        "---\n_Auto-generated by sindustries-weekly-review lobster._"
    )
    pr_result = run([
        "gh", "pr", "create",
        "--title", f"content(weekly-review): {review_date}",
        "--body", pr_body,
        "--base", "main",
    ])
    pr_url = pr_result.stdout.strip()

    result = {
        **stdin_data,
        "branch": branch,
        "pr_url": pr_url,
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
