-- Add a `pending` value to the `ApprovalState` enum: the durable
-- "this required gate has a row, but the gate has not been granted yet"
-- state. Replaces the `revoked`-as-outstanding hack documented in
-- docs/specs/add-ash-qa-agent-verifier-gate-tech-design.md (task f6a4d56a)
-- and adds the durable backing for task d9cd8a83.
--
-- Just `ALTER TYPE ... ADD VALUE` — no recreate-enum dance. We only
-- need the value to exist; we never reference `pending` from within
-- this same migration (the task-creation transaction in
-- services/tasks-api/src/routes/tasks.ts that first writes `pending`
-- rows lands in the same PR but only fires after the migration
-- commits). Enum value order is cosmetic — equality checks don't
-- depend on ordinal position, and the Prisma client doesn't either.
-- `IF NOT EXISTS` keeps the migration a no-op on a partial rollout.
ALTER TYPE "ApprovalState" ADD VALUE IF NOT EXISTS 'pending';

-- Preflight (run before applying):
--   SELECT state, count(*) FROM "TaskApproval" GROUP BY state;
-- Expected: zero `pending` rows; any count of `approved` and `revoked`
--   rows. No production code currently writes `pending`; this migration
--   only adds the enum value.
--
-- Post-apply (run after):
--   SELECT state, count(*) FROM "TaskApproval" GROUP BY state;
-- Expected: same shape as preflight — zero `pending`, any count of
--   `approved` and `revoked`. The migration is non-destructive.
--
-- Rollback (if the migration must be reversed on a fresh database):
--   -- Postgres disallows `ALTER TYPE ... DROP VALUE` inside a transaction,
--   -- so on a fresh DB the cleanest reverse is to rebuild the enum without
--   -- `pending` and re-cast the column. This drops any `pending` rows
--   -- created between deploy and revert (none should exist pre-deploy).
--   CREATE TYPE "ApprovalState_old" AS ENUM ('approved', 'revoked');
--   ALTER TABLE "TaskApproval" ALTER COLUMN state TYPE "ApprovalState_old"
--     USING state::text::"ApprovalState_old";
--   DROP TYPE "ApprovalState";
--   ALTER TYPE "ApprovalState_old" RENAME TO "ApprovalState";
