#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# shellcheck source=./mode-env.sh
source "$ROOT_DIR/scripts/dev/mode-env.sh"

# argv from Makefile > env var > default on
OBSERVABILITY="${1:-${OBSERVABILITY:-1}}"
export OBSERVABILITY

# shellcheck source=./port-cleanup.sh
source "$ROOT_DIR/scripts/dev/port-cleanup.sh"

expected_db_port_for_api_port() {
  case "$1" in
    4000) echo "6432" ;;
    4001) echo "7432" ;;
    *) echo "" ;;
  esac
}

EXPECTED_DB_PORT="$(expected_db_port_for_api_port "$TASKS_API_PORT")"
if [[ -n "$EXPECTED_DB_PORT" && "$POSTGRES_PORT" != "$EXPECTED_DB_PORT" ]]; then
  echo "Unsafe mode configuration: API port $TASKS_API_PORT expects DB port $EXPECTED_DB_PORT, got $POSTGRES_PORT." >&2
  echo "Check scripts/dev/mode-env.sh before starting the stack." >&2
  exit 1
fi

if ! command -v colima >/dev/null 2>&1; then
  echo "colima is required but not installed." >&2
  exit 1
fi

if ! command -v tilt >/dev/null 2>&1; then
  echo "tilt is required but not installed." >&2
  exit 1
fi

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker CLI is required but not installed." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
  echo "docker compose (plugin) or docker-compose is required but not installed." >&2
  exit 1
fi

if ! colima status >/dev/null 2>&1; then
  echo "Starting Colima..."
  colima start
fi

# Preflight: clear stale local listeners for this mode before Tilt boots.
cleanup_mode_ports

append_env_local_overrides() {
  local env_file="$1"
  local local_file="${env_file}.local"

  if [[ ! -f "$local_file" ]]; then
    return 0
  fi

  {
    echo
    echo "# Local overrides from $(basename "$local_file")"
    # Only allow a small, explicit set of vars to be merged to avoid surprises.
    # (This is primarily for secrets that shouldn't be auto-generated.)
    grep -E '^(AKAHU_CLIENT_ID|AKAHU_CLIENT_SECRET|AKAHU_REDIRECT_URI|AKAHU_DEV_USER_ACCESS_TOKEN)=' "$local_file" || true
  } >>"$env_file"
}

cat > "$ROOT_DIR/$TASKS_API_ENV_FILE" <<EOF
# Auto-generated by scripts/dev/up.sh for MODE=$MODE
PORT=$TASKS_API_PORT
DATABASE_URL="$DATABASE_URL"
CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS"
EOF

if [[ "$OBSERVABILITY" == "1" ]]; then
  cat >> "$ROOT_DIR/$TASKS_API_ENV_FILE" <<EOF

# OpenTelemetry (on: stack infra/docker-compose.observability.yml; default unless OBSERVABILITY=0)
OTEL_SERVICE_NAME=tasks-api
OTEL_SERVICE_NAMESPACE=sindustries
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:$OTLP_HTTP_PORT
OTEL_TRACES_EXPORTER=otlp
OTEL_METRICS_EXPORTER=otlp
OTEL_LOGS_EXPORTER=none
OTEL_ENVIRONMENT=$MODE
EOF
else
  cat >> "$ROOT_DIR/$TASKS_API_ENV_FILE" <<EOF

# OpenTelemetry off (make up OBSERVABILITY=0; avoids export errors when collector is down)
OTEL_SDK_DISABLED=1
EOF
fi

cat > "$ROOT_DIR/$BUDGET_API_ENV_FILE" <<EOF
# Auto-generated by scripts/dev/up.sh for MODE=$MODE
PORT=$BUDGET_API_PORT
DATABASE_URL="$BUDGET_DATABASE_URL"
CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS"
EOF

append_env_local_overrides "$ROOT_DIR/$BUDGET_API_ENV_FILE"

echo "Starting $MODE stack"
echo "  API: $TASKS_API_BASE_URL"
echo "  Budget API: $BUDGET_API_BASE_URL"
echo "  App: http://localhost:$TASKS_APP_PORT"
echo "  Postgres: localhost:$POSTGRES_PORT/$POSTGRES_DB"
if [[ "$OBSERVABILITY" == "1" ]]; then
  echo "  Observability: Grafana http://localhost:$GRAFANA_PORT (Tempo :$TEMPO_PORT, Prometheus :$PROMETHEUS_PORT, OTLP :$OTLP_HTTP_PORT)"
fi

cd "$ROOT_DIR"
exec env \
  TILT_OBSERVABILITY="$OBSERVABILITY" \
  OBSERVABILITY="$OBSERVABILITY" \
  MODE="$MODE" \
  tilt up --file infra/tilt/Tiltfile --port "$TILT_PORT"
