import '@testing-library/jest-dom/vitest';
import React from 'react';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';
import { DesignSystemPage } from './DesignSystemPage.jsx';

describe('DesignSystemPage', () => {
  it('renders the design system specimen', async () => {
    const user = userEvent.setup();
    render(<DesignSystemPage backHref="/" backLabel="← Tasks" />);

    expect(screen.getByRole('heading', { name: 'Sindustries design system' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Pulse / React' })).toBeInTheDocument();
    expect(screen.getByText('Components')).toBeInTheDocument();
    expect(screen.queryByText('Code catalog')).not.toBeInTheDocument();
    const componentsSection = screen.getByText('Components').closest('section');
    expect(within(componentsSection).getByRole('heading', { name: 'Buttons' })).toBeInTheDocument();
    expect(within(componentsSection).getByRole('heading', { name: 'Form controls' })).toBeInTheDocument();
    expect(within(componentsSection).getAllByText('CODE').length).toBeGreaterThan(1);
    expect(within(componentsSection).getByText(/pen:xBc88/)).toBeInTheDocument();
    expect(within(componentsSection).getByText(/variants: primary, secondary/)).toBeInTheDocument();
    expect(within(componentsSection).getByText(/pen:Tn1Ii/)).toBeInTheDocument();
    expect(within(componentsSection).getByText('Modal/Task Card')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Input Group/Title')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Select Group/Priority')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Divider/Dashed')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Divider/Subtle')).toBeInTheDocument();
    expect(within(componentsSection).getByRole('heading', { name: 'Dropdown' })).toBeInTheDocument();
    expect(within(componentsSection).getByText(/pen:vsaL0/)).toBeInTheDocument();
    expect(within(componentsSection).getByText('Toast/Info')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Toast/Success')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Toast/Error')).toBeInTheDocument();
    expect(within(componentsSection).getByText('Rover status update')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Default' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Secondary' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Destructive' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Outline' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Ghost' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Display primary' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Display outline' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Display ghost' })).toBeInTheDocument();
    expect(screen.getByText('Button/Default')).toBeInTheDocument();
    expect(screen.getByText('Button/Display/Primary')).toBeInTheDocument();
    expect(screen.getByText('Tertiary headers')).toBeInTheDocument();
    const pulsePage = screen.getByRole('heading', { name: 'Pulse / React' }).closest('section');
    expect(pulsePage).toBeTruthy();
    const surfacesBlock = within(pulsePage).getByRole('heading', { name: 'Surfaces' }).closest('.si-specimen-surface-block');
    expect(surfacesBlock).toBeTruthy();
    expect(within(surfacesBlock).getByRole('heading', { name: 'Surface Section Header' })).toBeInTheDocument();
    expect(within(surfacesBlock).getByText('Section Header')).toBeInTheDocument();
    expect(within(surfacesBlock).getByText('Fields')).toBeInTheDocument();
    expect(within(surfacesBlock).queryByLabelText('Title')).not.toBeInTheDocument();
    const componentsHeading = within(pulsePage).getByText('Components');
    expect(surfacesBlock.compareDocumentPosition(componentsHeading) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    expect(screen.getByText('Color')).toBeInTheDocument();
    expect(screen.getByText('Color labels')).toBeInTheDocument();
    expect(screen.getByText('Space')).toBeInTheDocument();
    expect(screen.getByText('Radius')).toBeInTheDocument();
    expect(screen.getByText('10')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: '← Tasks' })).toHaveAttribute('href', '/');

    const shell = screen.getByRole('main');
    const toggle = screen.getByRole('button', { name: 'Switch to light theme' });

    expect(shell).toHaveAttribute('data-si-theme', 'dark');
    await user.click(toggle);
    expect(shell).toHaveAttribute('data-si-theme', 'light');
    expect(screen.getByRole('button', { name: 'Switch to dark theme' })).toBeInTheDocument();
  });
});
